### ISSUE TITLE
It would be nice if it has an option to skip uploading artifacts.

### ISSUE THREAD

**Issue by 417-72KI** [kishikawakatsumi/xcresulttool#207]
I have already uploaded artifacts in previous steps. 
[Here](https://github.com/417-72KI/MockUserDefaults/actions/runs/2075159889) is an example.

In this case, artifacts are duplicated and will be a risk of storage pressure ([ref](https://pc.atsuhiro-me.net/entry/2021/02/05/095605)).

![image](https://user-images.githubusercontent.com/4150060/161203680-f1699377-7ae3-47fa-ac8b-708420acdf13.png)

**Comment by sergiocampama** [comment]
this action is great, but I can't use it until it supports optional uploads, as my result bundle for some reason is so big it's just using all of my storage. I tried forking as well, but there are no instructions to rebuild it, do you have those handy by any chance?

**Comment by sergiocampama** [comment]
https://github.com/kishikawakatsumi/xcresulttool/pull/211 is one attempt at it

**Comment by kishikawakatsumi** [comment]
Fixed by https://github.com/kishikawakatsumi/xcresulttool/pull/211 Thanks @sergiocampama

**Comment by kishikawakatsumi** [comment]
Released v1.4.0
