### ISSUE TITLE
Total test count off by as many empty test files

### ISSUE THREAD

**Issue by hanneskaeufler** [kishikawakatsumi/xcresulttool#63]
Great little plugin 🥇 thanks for writing it.

My overview shows a slightly confusing total # of tests vs. passed tests:

<img width="777" alt="Bildschirmfoto 2021-11-20 um 11 58 31" src="https://user-images.githubusercontent.com/68024/142723786-57fe70cc-0aa8-449b-856d-91cf08c9933d.png">

Can be traced down to:
<img width="781" alt="Bildschirmfoto 2021-11-20 um 11 58 45" src="https://user-images.githubusercontent.com/68024/142723795-7f9c0ff7-0e6e-4491-97f7-09a32302cf14.png">
>

which, granted, is an empty test case:

```
import XCTest

class OnboardingViewTests: XCTestCase {}
```

I'd kind of expect this to not report as a test case, what do you think?

**Comment by hanneskaeufler** [comment]
Tested with both v1 and v1.3.0

**Comment by kishikawakatsumi** [comment]
@hanneskaeufler Thanks for the report. I agree with you, I fixed it in v1.3.1.
