### ISSUE TITLE
Possible to share the source code for xcresulttool-file.herokuapp.com/file ?

### ISSUE THREAD

**Issue by jverkoey** [kishikawakatsumi/xcresulttool#652]
I was trying to figure out how this action is able to upload images for display in the results, and noticed the use of the `xcresulttool-file.herokuapp.com/file` service to do so. Is it possible to share the source for this service? I'm curious how the images are being attached to the camo service and would like to reproduce that behavior specifically in order to build a screenshot grid action.

**Comment by kishikawakatsumi** [comment]
https://github.com/kishikawakatsumi/xcresulttool-file

^ Here is the source code.

To display an image in a GitHub action, you cannot reference a local file and must upload it over the internet. However, files referenced over the network are automatically downloaded to GitHub, and the link to the image is eventually hosted on GitHub. So you don't need to store the image permanently, you just need to reference it for a moment.
