### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by JohanAlbrectsen** [kishikawakatsumi/xcresulttool#691]
I get the following error:

```
Run kishikawakatsumi/xcresulttool@v1
[2](step:7:2)
  with:
[3](step:7:3)
    path: TestResults.xcresult
[4](step:7:4)
    token: ***
[5](step:7:5)
    title: Xcode test results
[6](step:7:6)
    show-passed-tests: true
[7](step:7:7)
    show-code-coverage: true
[8](step:7:8)
    upload-bundles: always
[9](step:7:10)
Error: Resource not accessible by integration
```

It works perfectly, it generates the results page beautifully, but it throws this error. Is there a way I can avoid this error with some flags?

**Comment by kishikawakatsumi** [comment]
@JohanAlbrectsen 

Does this answer solve the problem?
https://github.com/kishikawakatsumi/xcresulttool/discussions/630#discussioncomment-4929085

**Comment by ykws** [comment]
me too.

I checked the discussions https://github.com/kishikawakatsumi/xcresulttool/discussions/630#discussioncomment-6642685, but only pull request still error, the following issue.

- https://github.com/yumemi-inc/ios-training/issues/57

@kishikawakatsumi let me know any check points.

**Comment by ykws** [comment]
@kishikawakatsumi Our problem has been fixed.

@JohanAlbrectsen Please check the permissions.  We need `pull_request_target` if the repository is forked.

- refs https://github.com/yumemi-inc/ios-training/pull/58

**Comment by kishikawakatsumi** [comment]
See https://github.com/kishikawakatsumi/xcresulttool/discussions/630

**Comment by mpt3ch** [comment]
[_**![image](https://github.com/kishikawakatsumi/xcresulttool/assets/67135801/6b2cc5fe-3607-44dd-8d8b-75043b1092a8)**_]()
